# run on container environment
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

language: php

notifications:
    email:
        on_success: change
        on_failure: always

php:
    - 7.2

env:
  global:
    # WPORG_PASSWORD
    - secure: "OBRXJmLZFp3moLc+qH9N130p+TGWeFHlVCcBsx7DJTP4gkBN8Gtwt7EvGXnh+BhYQ1OtAHA4idr6rnN3udY9xFH2zWBGHpHIiD25oY3soeU2wrCq5kEtk5I80tb6LqYutApuNLh4KlUo0EnJ0WCkxSbImHcvjvZIAIfNqC0h8+0="
  matrix:
    # WP latest stable:
    - WP_VERSION=*
    # WP nightly:
    - WP_VERSION=dev-nightly

jobs:
  include:
    - stage: deploy
      if: tag IS present
      before_script:
        - npm install
      script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script: npm run grunt deploy:ci
          on:
            tags: true

matrix:
    fast_finish: true

before_install:
    - |
      if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
        phpenv config-rm xdebug.ini
      fi

install:
    - travis_retry composer install --no-suggest
    - travis_retry composer require --dev --update-with-dependencies --no-suggest roots/wordpress="${WP_VERSION} || *" wp-phpunit/wp-phpunit="${WP_VERSION} || *"

script:
    - composer test
