# run on container environment
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

language: php

notifications:
    email:
        on_success: change
        on_failure: always

php:
    - 7.2
    - 5.6

env:
    # nightly:
    - WP_VERSION=nightly
    # latest stable:
    - WP_VERSION=latest

matrix:
    fast_finish: true

before_install:
    - |
      if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
        phpenv config-rm xdebug.ini
      fi

install:
    - travis_retry composer install

before_script:
    - php --version
    - travis_retry bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
    - bash bin/test.sh travis
