name: Test
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
      - 'master'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        php: ['7.3']
        wp: ['*', 'dev-nightly']
      fail-fast: false
    name: WP ${{ matrix.wp }} / PHP ${{ matrix.php }}
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Composer cache
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache
        key: ${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

    - name: PHPCS cache
      uses: actions/cache@v1
      with:
        path: tests/cache
        # This uses the hash of user-switching.php in its cache key because Actions doesn't support
        # always pulling in a cache file and simultaneously always updating it, unlike Travis.
        # This way we always pull in a cache file and refresh it with each new version of the plugin.
        key: ${{ matrix.php }}-phpcs-${{ hashFiles('user-switching.php') }}

    - name: Install PHP
      uses: shivammathur/setup-php@2.7.0
      with:
        php-version: ${{ matrix.php }}
        extensions: mysqli, xmlwriter
        coverage: none
      env:
        fail-fast: true

    - name: Debugging
      run: |
        php --version
        php -m
        composer --version
        mysql --version

    - name: Install dependencies
      run: |
        sudo systemctl start mysql.service
        composer install --prefer-dist --no-suggest
        composer require --dev --update-with-dependencies --no-suggest --prefer-dist roots/wordpress="${{ matrix.wp }} || *" wp-phpunit/wp-phpunit="${{ matrix.wp }} || *"

    - name: Run the tests
      run: composer test
      env:
        MYSQL_DATABASE: wordpress
        WP_TESTS_DB_PASS: root
